# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab2(self):
    self.driver.get("https://tutorialsninja.com/demo/")
    self.driver.set_window_size(1051, 797)
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    WebDriverWait(self.driver, 10000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".product-thumb h4 a")))
    self.driver.find_element(By.CSS_SELECTOR, ".product-thumb h4 a").click()
    self.driver.find_element(By.ID, "button-cart").click()
    self.driver.execute_script("window.scrollTo(0,368)")
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys("i phone")
    self.driver.find_element(By.CSS_SELECTOR, ".fa-search").click()
  
